version: '3.7'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - SERVER_ZILLIQA_KEY="REPLACEME" # DO NOT USE THIS IN PRODUCTION - This should be handled by your secret manager
    depends_on:
      - redis
    deploy:
      mode: global
    
  redis:
    image: redis
